# Eureka
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    preferIpAddress: true
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}

# Management
management:
  context-path: /
  security:
    enabled: false # just to see the zuul routes (/routes endpoint) without type a password

logging:
  level:
    com.netflix.discovery: 'ERROR'
    org.springframework.cloud: 'INFO'

# Server
server:
  port: ${info.application.port}
  session:
    timeout: 300
  tomcat:
    accesslog:
      enabled: true
      directory: ${logging.path}/
      prefix: access_log_${spring.application.index}
  compression:
    enabled: true

#Routes
zuul:
  host:
    connectTimeoutMillis: 5000
    socketTimeoutMillis: 20000
  prefix: /api
  ignored-services: hystrix, zipkin

# authentication users & roles
# for production environment it is better to persist into a database
# and avoid to put keys into configuration yaml and push it to git
# I just put here cause I'm afraid about the short time for the hackathon
auth:
  roles:
    - user
    - admin
  users:
    - skip:
        password: $2a$10$V9nZ9wpO/w3yha8Sv58HYO/aRnDiDPeVEBRneBCgAlZ09CnrVdKGu
        role: consumer
    - admin:
        password: $2a$10$BHU9RLum3OM3Ndn9ViEk9e3vOxvlQD.SPX9sIis6aw0vFYDmvg4Iy
        role: admin

---

spring:
  profiles: development

logging:
  level:
    com.netflix.discovery: 'OFF'